### ISSUE TITLE
Remove all "registering is easy" screens

### ISSUE THREAD

**Issue by canuckjacq** [HackForEquality/android-app#31]

**Comment by AlanCowap** [comment]
Addressing this in new branch: info_screens. https://github.com/HackForEquality/android-app/tree/info_screens

**Comment by AlanCowap** [comment]
There's an additional bug here. The ActionBar colour does not (edit: always)match the fragment colour - especially when you go back through the Info pages. I'll have a look at that too.

**Comment by Ankhwatcher** [comment]
Yeah that was bugging me too.

**Comment by canuckjacq** [comment]
:D I thought it looked kind of nifty. 
(but I'm fine with it being fixed too!)

**Comment by AlanCowap** [comment]
I fixed the one colour that was off slightly. The "nifty" bug I'll leave rather than spend time on, I had a quick look and see the problem, but the solution may not be so quick. So moving along...
@canuckjacq I'll upload an .apk to slack, (just for the info screens), if you're happy with it you can Close this issue.
